# Generated by Django 4.0.5 on 2023-02-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lasstName', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('pharmaceaticalLicence', models.FileField(blank=True, null=True, upload_to='pharmaceaticalLicence/')),
                ('operatingLicence', models.FileField(blank=True, null=True, upload_to='operatingLicence/')),
                ('email', models.EmailField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
