# Generated by Django 4.0.5 on 2023-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='lasstName',
            new_name='lastame',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='operatingLicence',
            new_name='operatinglicence',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='pharmaceaticalLicence',
            new_name='pharmaceaticallicence',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='phoneNumber',
            new_name='phonenumber',
        ),
    ]
