# Generated by Django 4.0.5 on 2023-02-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signapi', '0002_rename_firstname_useraccount_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='lastame',
            new_name='lastname',
        ),
    ]
