# Generated by Django 4.0.5 on 2023-03-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signapi', '0003_rename_lastame_useraccount_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='password2',
            new_name='password',
        ),
    ]
