# Generated by Django 4.0.5 on 2023-03-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signapi', '0004_rename_password2_useraccount_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='password',
            new_name='password2',
        ),
    ]
